---
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: "3"
services:
  node14:
    # Uncomment the next line to use a non-root user for all processes. You can also
    # simply use the "remoteUser" property in devcontainer.json if you just want VS Code
    # and its sub-processes (terminals, tasks, debugging) to execute as the user. On Linux,
    # you may need to update USER_UID and USER_GID in .devcontainer/Dockerfile to match your
    # user if not 1000. See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: vscode

    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: node
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    env_file: .env.dev

    ports:
      - 5000:5000
      - 9000:9000

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - /home/vjcdev/vsc/orientation-react:/workspace

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

  db:
    image: mariadb
    restart: always
    container_name: orientation_react_db
    ports:
      - 3307:3306
    expose:
      - 3307
    volumes:
      - orientation-react-mariadb:/var/lib/mariadb/data
    environment:
      MARIADB_ROOT_PASSWORD: password

volumes:
  orientation-react-mariadb:
    driver: local
